### ISSUE TITLE
Errors in latest deno release

### ISSUE THREAD

**Issue by hmt** [udibo/http_error#1]
```
error: TS2304 [ERROR]: Cannot find name 'ErrorInit'.
export interface HttpErrorInit extends ErrorInit {
                                       ~~~~~~~~~
    at https://deno.land/x/http_error@0.1.2/mod.ts:4:40

TS2559 [ERROR]: Type 'HttpErrorInit' has no properties in common with type 'ErrorOptions'.
    super(message, init);
                   ~~~~
    at https://deno.land/x/http_error@0.1.2/mod.ts:104:20

Found 2 errors.
```

**Comment by KyleJune** [comment]
I believe the issue is that ErrorInit was replaced with ErrorOptions recently by TypeScript. I'll update this interface to extend that instead.

https://github.com/microsoft/TypeScript/blob/363e3a78f4def6084cc7371c8b1104485a7fe5f8/src/lib/es2022.error.d.ts

I probably won't get around to it until later this week.

**Comment by hmt** [comment]
No worries. Very kind of you!

**Comment by hmt** [comment]
Thank you!
